
version: "3"

networks:
  coprocessor-network:
    name: coprocessor-network
    driver: bridge

services:
  anvil:
    build:
      context: .
      dockerfile: Dockerfile-anvil
    container_name: anvil
    ports:
      - 127.0.0.1:8545:8545
    volumes:
      - ./env/eigenlayer/anvil/avs-and-eigenlayer-deployed-anvil-state.json:/root/.anvil/state.json
      - ./:/cartesi-lambada-coprocessor/

    command: /cartesi-lambada-coprocessor/env/eigenlayer/anvil/run-anvil-devnet.sh

    healthcheck:

      test: bash -c "[ -f /cartesi-lambada-coprocessor/env/eigenlayer/anvil/devnet-operators-ready.flag ]"
      interval: 3s
      retries: 300
      start_period: 15s

    networks:
      - coprocessor-network

  operator:
    image: ghcr.io/zippiehq/cartesi-coprocessor-operator:latest
    container_name: cartesi-coprocessor-operator
    ports:
      - 127.0.0.1:3033:3033
    depends_on:
      anvil:
        condition: service_healthy
      setup-operator:
        condition: service_completed_successfully
    volumes:
      - ./demo-task:/operator/demo-task
    environment:
      SNAPSHOT_DIR: demo-task
      BLS_PRIVATE_KEY: ${OPERATOR_BLS_KEY:-13219903133444082589215719304558031505888625714969126489655808257015621956774}
    command: bash -c "/operator/cartesi-coprocessor-operator"
    networks:
      - coprocessor-network

  setup-operator:
    image: ghcr.io/zippiehq/cartesi-coprocessor-operator:latest
    container_name: cartesi-coprocessor-setup-operator
    ports:
      - 127.0.0.1:3033:3033
    depends_on:
      anvil:
        condition: service_healthy
    volumes:
      - ./contracts/script/output/coprocessor_deployment_output_devnet.json:/operator/contracts/script/output/coprocessor_deployment_output_devnet.json
      - ./contracts/script/input/deployment_parameters_devnet.json:/operator/contracts/script/input/deployment_parameters_devnet.json
    environment:
      OPERATOR_BLS_KEY: ${OPERATOR_BLS_KEY:-13219903133444082589215719304558031505888625714969126489655808257015621956774}
    command: bash -c "/operator/setup-operator --operator-private-key 0xc276a0e2815b89e9a3d8b64cb5d745d5b4f6b84531306c97aad82156000a7dd7 --http-endpoint http://anvil:8545 --strategy-deposit-address 0x09635F643e140090A9A8Dcd712eD6285858ceBef --strategy-deposit-amount 10 --chain-writer-reader-addresses contracts/script/input/deployment_parameters_devnet.json --avs-registry-writer-addresses contracts/script/output/coprocessor_deployment_output_devnet.json --socket http://operator:3033"
    networks:
      - coprocessor-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    networks:
      - coprocessor-network

  solver:
    image: ghcr.io/zippiehq/cartesi-coprocessor-solver:latest
    container_name: cartesi-coprocessor-solver
    ports:
      - 127.0.0.1:3034:3034
    depends_on:
      anvil:
        condition: service_healthy
      setup-operator:
        condition: service_completed_successfully
    volumes:
      - ./config.toml:/cartesi-coprocessor-solver/config.toml
    environment:
      - RUST_LOG=trace
    networks:
      - coprocessor-network